 export const categories = [
    "All",
    "Gaming",
    "Music",
    "Sports",
    "News",
    "Entertainment",
    "Education",
    "Technology",
    "Comedy",
    "Travel",
    "Food",
    "Fashion",
    "Health",
    "Science",
    "Documentary",
    "Animation",
    "Movies",
    "TV Shows",
    "Vlogs",
    "Tutorials",
    "Reviews",
    "Other",
  ];